'use client';
import {useEffect,useState} from 'react';
import {copy, type Locale,slugs} from './copy';
const anchors=['work','capabilities','about','contact'];
export default function Home(){
 const [locale,setLocale]=useState<Locale>('en'); const [theme,setTheme]=useState('dark'); const [mode,setMode]=useState('bold'); const [ready,setReady]=useState(false); const [filter,setFilter]=useState('all'); const [skill,setSkill]=useState(0); const [project,setProject]=useState<number|null>(null);
 const t=copy[locale];
 useEffect(()=>{try{const l=localStorage.getItem('locale');if(l==='ar'||l==='sv'||l==='en')setLocale(l);if(localStorage.getItem('theme')==='light')setTheme('light');if(localStorage.getItem('mode')==='calm')setMode('calm')}catch{}setReady(true); const sync=()=>{const slug=new URLSearchParams(location.search).get('project');setProject(slug&&slugs.includes(slug)?slugs.indexOf(slug):null)};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.documentElement.dataset.theme=theme;document.documentElement.dataset.mode=mode;if(ready)try{localStorage.setItem('locale',locale);localStorage.setItem('theme',theme);localStorage.setItem('mode',mode)}catch{}},[locale,theme,mode,ready]);
 function openProject(i:number|null){setProject(i);history.pushState(null,'',i===null?'#work':`?project=${slugs[i]}#project`)}
 return <><a className="skip" href="#main">{t.skip}</a><header><a className="brand" href="#" aria-label="Mohamed Amin">ma<span>↗</span></a><nav>{t.nav.map((n,i)=><a key={n} href={`#${anchors[i]}`}>{n}</a>)}</nav><div className="controls"><select aria-label={t.language} value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">EN</option><option value="ar">عربي</option><option value="sv">SV</option></select><button aria-label={t.theme} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☼':'◐'}</button><button className="mode" aria-label={t.mode} onClick={()=>setMode(mode==='bold'?'calm':'bold')}>{mode==='bold'?t.bold:t.calm}<span> ◇</span></button></div></header>
 <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dot"/>{t.eyebrow}</p><h1>{t.head[0]}<br/><span>{t.head[1]}</span><br/>{t.head[2]}<br/><em>{t.head[3]}</em></h1><p className="intro">{t.intro}</p><div className="actions"><a className="primary" href="#work">{t.explore}<span>↗</span></a><a className="text-link" href="https://github.com/Mo1Amin" target="_blank" rel="noreferrer">{t.github} ↗</a></div></div><div className="hero-art" aria-hidden="true"><div className="art-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="core"><span>m<span className="core-accent">a</span></span></div><span className="node node-web">&lt;/&gt;<small>WEB</small></span><span className="node node-ai">✳<small>AI / ML</small></span><span className="node node-mobile">▯<small>MOBILE</small></span><span className="coordinate">SYSTEM / AMIN<br/>30.00° N · BUILDING IDEAS</span><span className="art-caption">{t.note}</span><div className="art-index">01 — 03</div></div><div className="hero-bottom"><span>{t.scroll} ↓</span><span>WEB / MOBILE / AI</span></div></section>
 <div className="marquee" aria-hidden="true"><span>CREATIVE THINKING</span><b>✳</b><span>ENGINEERING MINDSET</span><b>✳</b><span>HUMAN EXPERIENCE</span><b>✳</b></div>
 <section id="work" className="section work"><div className="section-top"><div><p className="eyebrow">01 / {t.nav[0]}</p><h2>{t.selected}<span className="accent">.</span></h2><p>{t.selectedSub}</p></div><div className="filters">{[['all',t.all],['web',t.web],['mobile',t.mobile]].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div></div><div className="projects">{[0,1,2,3].filter(i=>filter==='all'||(filter==='web'?i===2:i===3)).map(i=><article className={`project p${i}`} key={i}><button className="project-visual" onClick={()=>openProject(i)} aria-label={`${t.details}: ${t.projects[i]}`}><span className="project-number">0{i+1}</span><div className="project-symbol">{['m / n','مـ','acm','✳'][i]}</div><span className="visual-word">{['MED NOTES','MYQAT','COMMUNITY, CONNECTED.','HUMAN × MACHINE'][i]}</span><span className="project-arrow">↗</span><small>{t.artifact}</small></button><div className="project-info"><p className="eyebrow">{t.tags[i]}</p><button className="project-title" onClick={()=>openProject(i)}>{t.projects[i]} <span>↗</span></button><p>{t.summaries[i]}</p></div></article>)}</div></section>
 {project!==null&&<section className="case-study section" id="project" aria-labelledby="case-title"><button className="text-link" onClick={()=>openProject(null)}>← {t.back}</button><p className="eyebrow">{t.tags[project]}</p><h2 id="case-title">{t.projects[project]}</h2><p>{t.summaries[project]}</p><h3>{t.role}</h3><p>{t.roles[project]}</p><p className="case-status">{t.release}</p></section>}
 <section className="section capabilities" id="capabilities"><p className="eyebrow">02 / {t.nav[1]}</p><h2>{t.capTitle}</h2><p>{t.capIntro}</p><div className="cap-layout"><div className="cap-tabs" role="tablist" aria-label={t.nav[1]}>{t.skills.map((s,i)=><button role="tab" aria-selected={skill===i} aria-controls="skill-panel" id={`skill-${i}`} key={s} onClick={()=>setSkill(i)}><span>0{i+1}</span>{s}<b>{skill===i?'↗':'+'}</b></button>)}</div><div id="skill-panel" role="tabpanel" aria-labelledby={`skill-${skill}`} className="skill-panel"><div className="skill-glyph" aria-hidden="true">{['{ }','▯','✳','⌘'][skill]}</div><h3>{t.skills[skill]}</h3><p>{t.skillDesc[skill]}</p></div></div><div className="workflow"><span>↳</span><div><h3>{t.workflow}</h3><p>{t.workflowText}</p></div></div></section>
 <section className="section about" id="about"><div><p className="eyebrow">03 / {t.aboutLabel}</p><h2>{t.aboutTitle}</h2><p className="about-copy">{t.about}</p><div className="signature">Mohamed Amin<span>↗</span></div></div><div className="proof"><article><span className="proof-icon">↗</span><div><small>SU ACM STUDENT CHAPTER</small><h3>{t.leadTitle}</h3><p>{t.lead}</p></div></article><article><span className="proof-icon grade">A+</span><div><small>FLUTTER × ML</small><h3>{t.grade}</h3><p>{t.gradeText}</p></div></article><article><span className="proof-icon">⌁</span><div><small>{t.education}</small><h3>{t.edu}</h3><p>{t.cert}</p></div></article></div></section>
 <section className="journey section" aria-labelledby="journey-title"><div className="section-top"><div><p className="eyebrow">04 / {t.education}</p><h2 id="journey-title">The work<br /><span className="accent">behind the work.</span></h2></div><p>{t.about}</p></div><div className="journey-grid"><article><span>01</span><small>SU ACM STUDENT CHAPTER</small><h3>{t.leadTitle}</h3><p>{t.lead}</p></article><article><span>02</span><small>FLUTTER × ML</small><h3>{t.grade}</h3><p>{t.gradeText}</p></article><article><span>03</span><small>{t.education}</small><h3>{t.edu}</h3><p>{t.cert}</p></article></div></section><section className="contact section" id="contact"><p className="eyebrow">05 / {t.next}</p><h2>{t.contact}<span className="accent">↗</span></h2><div><p>{t.contactText}</p><a className="primary" href="https://github.com/Mo1Amin" target="_blank" rel="noreferrer">{t.contactLink} ↗</a></div></section></main><footer><a className="brand" href="#">ma<span>↗</span></a><p>{t.footer}</p><span>© 2026 MOHAMED AMIN</span></footer></>
}
